services:
  stratum-mongo:
    image: mongo:latest
    container_name: stratum-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=m11615
      - MONGO_INITDB_DATABASE=stratum
    volumes:
      - stratum-mongo-volume:/data/db
      - ./initialisation/mongo:/docker-entrypoint-initdb.d
    networks:
      - stratum-network
    restart: no

  stratum-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: stratum-server
    ports:
      - "3000:3000"
    networks:
      - stratum-network
    depends_on:
      - stratum-mongo
    restart: no

  stratum-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: stratum-client
    ports:
      - "3001:3001"
    networks:
      - stratum-network
    extra_hosts:
      - "server:host-gateway"
    depends_on:
      - stratum-server
    restart: no

volumes:
  stratum-mongo-volume:
    driver: local

networks:
  stratum-network:
    driver: bridge
