resources:
  - ./mongo/deployment.yaml
  - ./mongo/service.yaml
  - ./mongo/pv.yaml
  - ./mongo/pvc.yaml
  - ./server/deployment.yaml
  - ./server/service.yaml
  - ./client/deployment.yaml
  - ./client/service.yaml
